services:
  segmenter-be:
    build:
      context: ./Segmenter-BE-Components
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: python app.py
    depends_on:
      - segmenter-fe

  segmenter-fe:
    build:
      context: ./Segmenter-FE-Components
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ./serve.sh
