services:
  segmenter-fe:
    image: danielson05/cnh_test-segmenter-fe:latest
    build:
      context: ./Segmenter-FE-Components
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - segmenter-be
  segmenter-be:
    image: danielson05/cnh_test-segmenter-be:latest
    build:
      context: ./Segmenter-BE-Components
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
